RazorPagesGeneral/Pages/Employees/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesLessons.Models;
using RazorPagesLessons.Services;

namespace RazorPagesGeneral.Pages.Employees
{
    public class DeleteModel : PageModel
    {
        private readonly IEmployeeRepository _employeeRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public DeleteModel(IEmployeeRepository employeeRepository, IWebHostEnvironment webHostEnvironment)
        {
            _employeeRepository = employeeRepository;
            _webHostEnvironment = webHostEnvironment;
        }

        [BindProperty]
        public Employee Employee { get; set; }

        public IActionResult OnGet(int id)
        {
            Employee = _employeeRepository.GetEmployee(id);

            if (Employee == null)
                return RedirectToPage("/NotFound");

            return Page();
        }

        public IActionResult OnPost()
        {
            Employee deletedEmployee = _employeeRepository.Delete(Employee.Id);

            if (deletedEmployee.PhotoPath != null)
            {
                string filePath = Path.Combine(_webHostEnvironment.WebRootPath, "images", deletedEmployee.PhotoPath);

                if (deletedEmployee.PhotoPath != "noimage.png")
                    System.IO.File.Delete(filePath);
            }


            if (deletedEmployee == null)
                return RedirectToPage("/NotFound");

            return RedirectToPage("Employees");
        }
    }
}

RazorPagesGeneral/Pages/Employees/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesLessons.Models;
using RazorPagesLessons.Services;

namespace RazorPagesGeneral.Pages.Employees
{
    public class DetailsModel : PageModel
    {
        private readonly IEmployeeRepository _employeeRepository;

        public DetailsModel(IEmployeeRepository employeeRepository)
        {
            _employeeRepository = employeeRepository;
        }

        public Employee Employee { get; private set; }

        public void OnGet(int id)
        {
            Employee = _employeeRepository.GetEmployee(id);
        }
    }
}

RazorPagesGeneral/Pages/Employees/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesLessons.Models;
using RazorPagesLessons.Services;

namespace RazorPagesGeneral.Pages.Employees
{
    public class EditModel : PageModel
    {
        private readonly IEmployeeRepository _employeeRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public EditModel(IEmployeeRepository employeeRepository, IWebHostEnvironment webHostEnvironment)
        {
            _employeeRepository = employeeRepository;
            _webHostEnvironment = webHostEnvironment;
        }

        [BindProperty]
        public Employee Employee { get; set; }       
        
        [BindProperty]
        public IFormFile Photo { get; set; }

        [BindProperty]
        public bool Notify { get; set; }
        public string Message { get; set; }

        public IActionResult OnGet(int? id)
        {
            if (id.HasValue)
                Employee = _employeeRepository.GetEmployee(id.Value);
            else
                Employee = new Employee();

            if (Employee == null)
                return RedirectToPage("/NoyFound");

            return Page();
        }

        public IActionResult OnPost()
        {
            if(ModelState.IsValid)
            {
                if (Photo != null)
                {
                    if (Employee.PhotoPath != null)
                    {
                        string filePath = Path.Combine(_webHostEnvironment.WebRootPath, "images", Employee.PhotoPath);

                        if(Employee.PhotoPath != "noimage.png")
                            System.IO.File.Delete(filePath);
                    }
                    Employee.PhotoPath = ProcessUploadedFile();
                }

                if (Employee.Id > 0)
                {
                    Employee = _employeeRepository.Update(Employee);

                    TempData["SuccessMessage"] = $"Оновлення {Employee.Name} успішне!";
                }
                else
                {
                    Employee = _employeeRepository.Add(Employee);

                    TempData["SuccessMessage"] = $"Додавання {Employee.Name} успішне!";
                }

                return RedirectToPage("Employees");
            }

            return Page();
            
        }

        public void OnPostUpdateNotificationPreference(int id)
        {
            if (Notify)
                Message = "Дякуємо, що ввімкнули сповіщення";
            else
                Message = "Ви вимкнули сповіщення на email";

            Employee = _employeeRepository.GetEmployee(id);
        }

        private string ProcessUploadedFile()
        {
            string uniqueFileName = null;
            if (Photo != null)
            {
                string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + Photo.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                using(var fs = new FileStream(filePath, FileMode.Create))
                {
                    Photo.CopyTo(fs);
                }
            }
            return uniqueFileName;
        }
    }
}

RazorPagesGeneral/Pages/Employees/Employees.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesLessons.Services;
using RazorPagesLessons.Models;

namespace RazorPagesGeneral.Pages.Employees
{
    public class EmployeesModel : PageModel
    {
        private readonly IEmployeeRepository _db;
        public EmployeesModel(IEmployeeRepository db)
        {
            _db = db;
        }
        public IEnumerable<Employee> Employees { get; set; }
        [BindProperty(SupportsGet = true)]
        public string SearchTerm { get; set; }

        public void OnGet()
        {
            Employees = _db.Search(SearchTerm);
        }
    }
}

RazorPagesGeneral/ViewComponents/HeadCountViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using RazorPagesLessons.Models;
using RazorPagesLessons.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RazorPagesGeneral.ViewComponents
{
    public class HeadCountViewComponent : ViewComponent
    {
        private readonly IEmployeeRepository _employeeRepository;

        public HeadCountViewComponent(IEmployeeRepository employeeRepository)
        {
            _employeeRepository = employeeRepository;
        }

        public IViewComponentResult Invoke(Dept? department = null)
        {
            var result = _employeeRepository.EmployeeCountByDept(department);
            return View(result);
        }

    }
}

RazorPagesGeneral/Pages/Employees/Delete.cshtml
@page "{id}"
@model RazorPagesGeneral.Pages.Employees.DeleteModel
@{
    ViewData["Title"] = "Видалення";
    ViewData["ShowButtons"] = false;
}

<h1 class="text-center" \>Підтвердження видалення</h1>

<div class="alert alert-danger">
    <div class="row">
        <div class="col-12 col-md-6 col-xl-4 offset-sm-0 offset-md-3 offset-xl-4">
            <partial name="_DisplayEmployeePartial" model="Model.Employee" view-data="ViewData" />
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-md-6 col-xl-4 offset-sm-0 offset-md-3 offset-xl-4">
            <div class="text-center text-secondary">
                <h4> ID працівника: <span class="text-primary">@Model.Employee.Id</span></h4><hr />
                <h4> Email працівника: <span class="text-primary">@Model.Employee.Email</span></h4><hr />
                <h4> Департамент: <span class="text-primary">@Model.Employee.Department</span></h4><hr />
            </div>
        </div>
    </div>
    <div>
        <div class="row">
            <div class="col text-center">
                <h5>Ви справді бажаєте видалити користувача - @Model.Employee.Name?</h5>

                <form method="post">
                    <button type="submit" class="btn btn-danger">Так</button>
                    <a class="btn btn-success" asp-page="/Employees/Employees">Ні</a>
                </form>
            </div>
        </div>
    </div>
</div>

RazorPagesGeneral/Pages/Employees/Details.cshtml
@page "{id}"
@model RazorPagesGeneral.Pages.Employees.DetailsModel
@{
    ViewData["Title"] = "Employee Details";

    // Шлях до фото
    var photoPath = $"/images/{Model.Employee.PhotoPath ?? "noimage.png"}";
}

<div class="row justify-content-center m-3">
    <div class="col-lg-8">
        @*@await Component.InvokeAsync("HeadCount", new { department = Model.Employee.Department})*@
        <vc:head-count department="@Model.Employee.Department"></vc:head-count>
    </div>
</div>

<div class="row justify-content-center m-3">
    <div class="col-lg-8">
        <div class="card cardBoxShadow">

            <div class="card-header cardHeaderStyle text-center">
                <h1>@Model.Employee.Name</h1>
            </div>

            <div class="card-body <!--cardBoxShadow-->  text-center">
                <div class="row">
                    <div class="col col-lg-9">
                        <h4 class="cardTextLeftFloating"> Employee ID: @Model.Employee.Id</h4>
                        <h4 class="cardTextLeftFloating"> Email: @Model.Employee.Email</h4>
                        <h4 class="cardTextLeftFloating"> Department: <span class="text-danger font-weight-bold">@Model.Employee.Department</span></h4>
                    </div>
                    <div class="col col-lg-3">
                        <div style="border-right: 1px solid rgba(0,0,0,.1);">
                            <img class="card-img-top imageThumbnail border border-primary" style="background-color: #dle7ff" src="@photoPath" asp-append-version="true"/>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <div class="card-footer text-center" style="background-color: rgba(0,0,0,0.25);">
                        <a asp-page="Employees" class="btn btn-success buttonShadow">Назад</a>
                        <a href="#" class="btn btn-primary buttonShadow">Редагувати</a>
                        <a href="#"  class="btn btn-danger buttonShadow">Видалити</a>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

RazorPagesGeneral/Pages/Employees/Edit.cshtml
@page "{id:min(1)?}/{handler?}"
@model RazorPagesGeneral.Pages.Employees.EditModel
@{ 
    var photoPath = $"/images/{Model.Employee.PhotoPath ?? "noimage.png"}";

    var pageTitle = Model.Employee.Id > 0 ? "Edit" : "Create";
    ViewData["Title"] = pageTitle;
}

<form method="post" asp-page-handler="UpdateNotificationPreference">
    <div class="row text-center notyfyBlock">
        <div class="col form-check">
            <h1>Налаштування сповіщень</h1>
            <input asp-for="Notify" class="form-check-input"/>
            <label asp-for="Notify" class="form-check-label">
                Надсилати сповіщення на e-mail коли мій профіль буде змінено
            </label><br />

            <button type="submit" class="btn btn-primary text-center">Оновити налаштування сповіщень</button>

            @if (!string.IsNullOrWhiteSpace(Model.Message))
            {
                <div class="alert alert-success">
                    <p class="p-3 mt-2">@Model.Message</p>
                </div>
            }

        </div>
    </div>
</form>

<hr />

<div asp-validation-summary="All" class="text-danger text-center"></div>

<!--Создаём форму редактирования-->
<form method="post" asp-page-handler="OnPost" class="mt-3" enctype="multipart/form-data">
    <!--Создаём скрытое поле для параметра ID-->
    <input type="hidden" asp-for="Employee.Id" />
    <input type="hidden" asp-for="Employee.PhotoPath" />

    <!--Добавляем поля редактирования-->
    <div class="row justify-content-center m-3">
        <div class="col col-lg-8">
            <div class="card cardBoxShadow">
                <div class="card-header cardHeaderStyle text-center">
                    <!--Добавляем поле редактирования имени-->
                    <div class="form-group row">
                        <label asp-for="Employee.Name" class="col col-lg-4 col-form-label text-right">Редагувати ім’я:</label>
                        <div class="col col-lg-6">
                            <input asp-for="Employee.Name" class="form-control" placeholder="@Model.Employee.Name" />
                            <!--Добавляем сообщение валидации формы-->
                            <span asp-validation-for="Employee.Name" class="text-danger"></span>
                        </div>
                    </div>

                </div>
                <div class="card-body cardBodyStyle text-center">
                    <div class="row">
                        <div class="col col-lg-9">
                            <h4 class="cardTextLeftFloating">Employee ID: @Model.Employee.Id</h4><hr />

                            <!--Добавляем поле редактирования e-mail-->
                            <div class="form-group row">
                                <label asp-for="Employee.Email" class="col col-lg-4 col-form-label text-right">Редагувати E-mail:</label>
                                <div class="col-12 col-lg-6">
                                    <input asp-for="Employee.Email" class="form-control mr-2" placeholder="@Model.Employee.Email" />
                                    <!--Добавляем сообщение валидации формы-->
                                    <span asp-validation-for="Employee.Email" class="text-danger"></span>
                                </div>
                            </div>
                            <hr />
                            <!--Добавляем поле редактирования департамента-->
                            <div class="form-group row">
                                <label asp-for="Employee.Department" class="col col-lg-4 col-form-label text-right">Редагувати Department:</label>
                                <div class="col-12 col-lg-6">
                                    <!--Создаём выпадающий список с департаментами-->
                                    <!--Необходимо подключить класс локально или глобально-->
                                    <select asp-for="Employee.Department" class="custom-select mr-2" asp-items="Html.GetEnumSelectList<Dept>()">
                                        <!--Добавляем начальный элемент выпадающего списка-->
                                        <option value="">Please Select</option>
                                    </select>
                                    <span asp-validation-for="Employee.Department" class="text-danger"></span>
                                </div>
                            </div>
                            <hr />
                        </div>

                        <div class="col-lg-3">
                            <div>

                                <img class="card-img-top imageThumbnail border border-primary" src="@photoPath" asp-append-version="true" />

                                <div class="custom-file">
                                    <input asp-for="Photo" class="custom-file-input form-control" />
                                    <label class="custom-file-label text-left">Click Here</label>
                                </div>

                            </div>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="card-footer text-center" style="background-color: rgba(0, 0, 0, 0.25);">
                                <button type="submit" class="btn btn-success buttonShadow">Update</button>
                                <a asp-page="index" class="btn btn-danger buttonShadow">Cancel</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @section Scripts{
        <script>
            $(document).ready(function () {
                $('.custom-file-input').on("change", function () {
                    var fileName = $(this).val().split("\\").pop();
                    $(this).next('.custom-file-label').html(fileName);
                });
            });
        </script>

        <partial name="_ValidationScriptsPartial" />
    }

</form>

RazorPagesGeneral/Pages/Employees/Employees.cshtml
@page
@model RazorPagesGeneral.Pages.Employees.EmployeesModel
@{
    ViewData["Title"] = "Employees";
    ViewData["ShowButtons"] = true;
}

@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success text-center">
        @TempData["SuccessMessage"]
    </div>
}

<form method="get" class="mb-3">
    <div class="input-group">
        <input class="form-control" asp-for="SearchTerm"/>
        <div class="input-group-append">
            <button type="submit" class="btn btn-primary">Пошук</button>
        </div>
    </div>
</form>

@*@await Component.InvokeAsync("HeadCount")*@
    <vc:head-count department="@null"></vc:head-count>

<h1>Працівники</h1>

<div class="row">
    @foreach (var item in Model.Employees)
    {
        <div class="col-12 col-sm-6 col-lg-4">
            <partial name="_DisplayEmployeePartial" model="item" view-data="ViewData"/>
        </div>
    }
</div>